 # PRINT MESSAGE
X = "HELLO WORLD"
print(X)

# ADD TWO NUMBER
A = 10
B = 20
print("sum is = ",(A + B))

# even or odd
num = int(input("enter a number : "))
if (num % 2 == 0):
    print("even")
else:
    print("odd")
    
# check leap year
year = int(input("enter year :"))
if year % 4 == 0:
    print("leap year")
else:
    print("not a leap year") 
    
# print pi value 
import math
print(math.pi) 

# store and print constant value
PI = 3.14
print(PI)